# -*- coding: utf-8 -*-
"""Task4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1P8tab9b5ZYct1K7o-9H7z2d6NByn-yP3

**LetsGrowMore**

Data Science Intern

Name:-Anuradha Ananda Nerkar

Image to Pencil Sketch with Python

Importing Libraries
"""

import cv2
from google.colab.patches import cv2_imshow

"""Loading Image"""

image=cv2.imread('/ganpati.jpg', 1)
cv2_imshow(image)

"""Converting to gray scale image"""

image_gray = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)

cv2_imshow(image_gray)

"""Inverting Image"""

image_invert = cv2.bitwise_not(image_gray)

cv2_imshow(image_invert)

"""Smoothing the image"""

image_smoothing = cv2.GaussianBlur(image_invert, (21, 21),sigmaX=0, sigmaY=0)

cv2_imshow(image_smoothing)

"""Final output As Pencil Sketch"""

def dodgeV2(x, y):

    return cv2.divide(x, 255 - y, scale=256)

final_image = dodgeV2(image_gray, image_smoothing)

cv2_imshow(final_image)

"""**Thank You**"""